# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10d8qKghtZaP2yYqYDh-1-naq0kbhZIB2
"""



print("hello")

item1=int(input())
item2=int(input())
item3=int(input())
total=item1+item2+item3
discount=(total*10)/100
if (total>50):
  print(total-discount)
else :print(total)